const tools = [
    { name: 'Kubernetes', category_short: 'cloud', category_full: 'Cloud & SRE', proficiency: 3, related: ['docker', 'prometheus', 'argo cd', 'cilium'], icon: 'https://cdn.simpleicons.org/kubernetes/326CE5', description: 'Orquestração de contêineres para automação, escalabilidade e gestão de aplicações.' },
    { name: 'AWS', category_short: 'cloud', category_full: 'Cloud & SRE', proficiency: 3, related: ['terraform', 'kubernetes', 'lambda'], icon: 'https://cdn.simpleicons.org/amazonaws/232F3E', description: 'Plataforma de nuvem líder para serviços de computação, armazenamento e bases de dados.' },
    { name: 'GitHub Actions', category_short: 'devops', category_full: 'DevSecOps', proficiency: 3, related: ['docker', 'snyk', 'terraform'], icon: 'https://cdn.simpleicons.org/githubactions/2088FF', description: 'Automação de workflows de CI/CD diretamente no seu repositório GitHub.' },
    { name: 'Terraform', category_short: 'cloud', category_full: 'Cloud & SRE', proficiency: 3, related: ['aws', 'gcp', 'azure', 'vault'], icon: 'https://cdn.simpleicons.org/terraform/7B42BC', description: 'Infraestrutura como Código para provisionar e gerir recursos de nuvem de forma segura e eficiente.' },
    { name: 'Python', category_short: 'app_data', category_full: 'Aplicação & Dados', proficiency: 3, related: ['pandas', 'scikit-learn', 'fastapi'], icon: 'https://cdn.simpleicons.org/python/3776AB', description: 'Linguagem versátil para backend, scripting, automação e análise de dados.' },
    { name: 'Datadog', category_short: 'ai', category_full: 'IA & AIOps', proficiency: 3, related: ['aws', 'kubernetes', 'prometheus'], icon: 'https://cdn.simpleicons.org/datadog/632ca6', description: 'Plataforma de observabilidade para monitoramento de infraestrutura, APM e gestão de logs.' },
    { name: 'Argo CD', category_short: 'devops', category_full: 'DevSecOps', proficiency: 3, related: ['kubernetes', 'helm', 'kustomize'], icon: 'https://cdn.simpleicons.org/argo/EF7B4D', description: 'Ferramenta de GitOps para Kubernetes que permite a entrega contínua declarativa.' },
    { name: 'Zero Trust', category_short: 'strategy', category_full: 'Arquitetura & Estratégia', proficiency: 3, related: ['cilium', 'istio', 'vault', 'keycloak'], icon: '<svg class="tool-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" /></svg>', description: 'Modelo de segurança que assume que nenhuma entidade, interna ou externa, é confiável por padrão.' },
    { name: 'Vertex AI', category_short: 'ai', category_full: 'IA & AIOps', proficiency: 2, related: ['gcp', 'kubeflow', 'tensorflow'], icon: 'https://cdn.simpleicons.org/googlecloud/4285F4', description: 'Plataforma unificada de ML do Google Cloud para construir, treinar e implementar modelos.' },
    { name: 'Snyk', category_short: 'devops', category_full: 'DevSecOps', proficiency: 2, related: ['github actions', 'docker', 'python'], icon: 'https://cdn.simpleicons.org/snyk/4C4A73', description: 'Ferramenta de segurança que encontra e corrige vulnerabilidades em código, dependências e contêineres.' },
    { name: 'Cypress', category_short: 'app_data', category_full: 'Aplicação & Dados', proficiency: 2, related: ['javascript', 'github actions'], icon: 'https://cdn.simpleicons.org/cypress/17202C', description: 'Framework de testes E2E de nova geração para aplicações web modernas.' },
    { name: 'DDD', category_short: 'strategy', category_full: 'Arquitetura & Estratégia', proficiency: 2, related: ['microservices', 'event-driven'], icon: '<svg class="tool-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a3.002 3.002 0 013.292-2.143 3.002 3.002 0 013.292 2.143m-6.584 0a3.002 3.002 0 003.292-2.143 3.002 3.002 0 003.292 2.143m0 0l-1 1m-5.584-7.857l1-1m0 0l1 1m-1-1v-2m0 2l-1 1m0-1l-1-1m0 0l-1 1m1-1v-2m-2-4v2m2-2l-1 1m0-1l1-1m0 0l1 1m-1-1v-2m0 2l1 1m0-1l1-1m0 0l1 1m-1-1v-2"></path></svg>', description: 'Abordagem de design de software que alinha o código às necessidades do negócio.' },
    { name: 'FinOps', category_short: 'strategy', category_full: 'Arquitetura & Estratégia', proficiency: 1, related: ['aws', 'gcp', 'azure', 'opencost'], icon: '<svg class="tool-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 10v-1m0-6h.01M6 12H5m14 0h-1m-1-5.414l.707-.707m-12.02 12.02l-.707-.707m12.02 0l.707.707M6.707 6.707L6 6"></path></svg>', description: 'Prática de gestão financeira na nuvem para otimizar os custos e maximizar o valor.' },
    { name: 'BigQuery', category_short: 'app_data', category_full: 'Aplicação & Dados', proficiency: 1, related: ['gcp', 'dbt', 'tableau'], icon: 'https://cdn.simpleicons.org/googlebigquery/4285F4', description: 'Data warehouse serverless e escalável do Google Cloud para análise de grandes volumes de dados.' },
];

const stepsData = [
    { id: 1, title: 'Diagnóstico', color: 'var(--orange-500)', icon: '<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" /></svg>', details: 'Analisamos a fundo a sua arquitetura, processos e dados para identificar os desafios e as oportunidades de melhoria que irão gerar maior impacto no negócio.' },
    { id: 2, title: 'Planeamento', color: '#f86d2f', icon: '<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 20l-5.447-2.724A1 1 0 013 16.382V5.618a1 1 0 011.447-.894L12 9l7.553-4.276A1 1 0 0121 5.618v10.764a1 1 0 01-.553.894L15 20l-3-1.5-3 1.5z" /></svg>', details: 'Desenhamos uma solução técnica e um roadmap estratégico. Esta fase é colaborativa, garantindo o alinhamento total entre a tecnologia e os seus objetivos.' },
    { id: 3, title: 'Adaptação', color: '#f66748', icon: '<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14 10l-2 1m0 0l-2-1m2 1v2.5M20 7l-2 1m2-1l-2-1m2 1v2.5M14 4l-2-1-2 1M4 7l2 1M4 7l2-1M4 7v2.5M12 21l-2-1m2 1l2-1m-2 1v-2.5M6 18l-2-1v-2.5M18 18l2-1v-2.5" /></svg>', details: 'Preparamos a sua aplicação para a nuvem, o que pode incluir refatoração de código, conteinerização (Docker) e adaptação de bases de dados.' },
    { id: 4, title: 'Implementação', color: '#f36161', icon: '<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 12h14M12 5l7 7-7 7" /></svg>', details: 'Criamos a infraestrutura como código (IaC) e automatizamos o deploy com pipelines de CI/CD, garantindo entregas rápidas e seguras.' },
    { id: 5, title: 'Segurança', color: '#f05b7a', icon: '<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" /></svg>', details: 'Integramos segurança em todas as etapas, desde a análise de código até ao monitoramento em tempo real, com uma abordagem Zero Trust.' },
    { id: 6, 'title': 'Otimização', color: 'var(--pink-500)', icon: '<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6" /></svg>', details: 'Implementamos observabilidade completa e AIOps para monitorar a performance, otimizar custos e garantir a evolução contínua do sistema.' }
];

const allProjects = [
    { id: 2, category: 'Cloud', title: 'Migração para Microsserviços K8s', description: 'Orquestração da migração de uma aplicação legada para microsserviços em Kubernetes.', challenge: 'Modernizar um monolito, melhorando a escalabilidade.', solution: 'Migração para microsserviços em Go no GKE, com Kafka para comunicação assíncrona e Cypress para testes de regressão.', result: 'Aumento de 40% na velocidade de deploy e redução de 90% no tempo de inatividade.', tools: [{ name: 'kubernetes', category: 'Cloud & SRE', usage: 'Orquestração de todos os microsserviços em um ambiente GKE escalável.' }, { name: 'go', category: 'Aplicação & Dados', usage: 'Linguagem principal para o desenvolvimento dos novos microsserviços.' }, { name: 'kafka', category: 'Aplicação & Dados', usage: 'Garantia de comunicação assíncrona e resiliência entre os serviços.' }], borderColor: 'interactive-border-sky', metric: { value: '-90%', label: 'Downtime', explanation: 'O tempo de inatividade da aplicação foi reduzido em 90%, garantindo maior disponibilidade para os utilizadores.' }, breakdown: { cloud: 60, app_data: 40 } },
    { id: 0, category: 'AIOps', title: 'Sistema Preditivo com AIOps', description: 'Sistema que usa ML para analisar métricas, prever anomalias e iniciar auto-remediação.', challenge: 'Reduzir o tempo de resolução (MTTR) de incidentes.', solution: 'Serviço em Python que consome métricas do Prometheus, usa Prophet para detetar anomalias e aciona runbooks do Ansible.', result: 'Resolução de 80% dos incidentes comuns sem intervenção humana e redução do MTTR em 60%.', tools: [{ name: 'python', category: 'Aplicação & Dados', usage: 'Linguagem usada para o serviço de análise e machine learning.' }, { name: 'prometheus', category: 'Cloud & SRE', usage: 'Coleta de métricas em tempo real de toda a infraestrutura.' }, { name: 'ansible', category: 'Cloud & SRE', usage: 'Automação da execução de runbooks para auto-remediação.' }], borderColor: 'interactive-border-purple', metric: { value: '-60%', label: 'MTTR', explanation: 'MTTR (Mean Time to Resolution) é o tempo médio para resolver um incidente. Reduzir este valor significa uma recuperação mais rápida de falhas.' }, breakdown: { ai: 50, devops: 50 } },
    { id: 4, category: 'Segurança', title: 'Implementação de Zero Trust', description: 'Segurança de rede granular em Kubernetes usando políticas de rede baseadas em identidade via eBPF.', challenge: 'Atender a requisitos de conformidade PCI-DSS.', solution: 'Substituição do CNI padrão por Cilium para criar políticas de rede de "negação por padrão" baseadas em identidade de serviço.', result: 'Arquitetura Zero Trust implementada, tornando a segurança mais dinâmica e robusta.', tools: [{ name: 'kubernetes', category: 'Cloud & SRE', usage: 'Base da orquestração onde a política de segurança foi aplicada.' }, { name: 'cilium', category: 'DevSecOps', usage: 'CNI que utiliza eBPF para aplicar políticas de rede a nível de identidade.' }, { name: 'ebpf', category: 'Cloud & SRE', usage: 'Tecnologia de base que permitiu a observabilidade e segurança a nível de kernel.' }], borderColor: 'interactive-border-pink', metric: { value: '100%', label: 'Conformidade PCI', explanation: 'Atingimos 100% de conformidade com os rigorosos requisitos do PCI-DSS, garantindo a segurança dos dados de pagamento.' }, breakdown: { devops: 70, cloud: 30 } },
    { id: 5, category: 'FinOps', title: 'Otimização de Custos Cloud', description: 'Redução de custos de nuvem através da implementação de OpenCost e automação de instâncias spot.', challenge: 'Reduzir a fatura de nuvem sem impactar a performance.', solution: 'Instalação do OpenCost em clusters Kubernetes para dar visibilidade de custos por time e criação de automações com Terraform para usar instâncias spot.', result: 'Economia de 35% na fatura mensal.', tools: [{ name: 'aws', category: 'Cloud & SRE', usage: 'Provedor de nuvem principal para a infraestrutura do projeto.'}, { name: 'opencost', category: 'Cloud & SRE', usage: 'Ferramenta usada para monitoramento de custos em Kubernetes.'}, { name: 'terraform', category: 'Cloud & SRE', usage: 'Automação do provisionamento de instâncias spot.'}], borderColor: 'interactive-border-green', metric: { value: '-35%', label: 'Custos Cloud', explanation: 'Reduzimos os custos mensais com a nuvem em 35% através de uma gestão financeira proativa (FinOps).' }, breakdown: { strategy: 50, cloud: 50 } },
    { id: 14, category: 'Data Engineering', title: 'Plataforma de Streaming', description: 'Implantação de um cluster Kafka para processamento de milhões de eventos em tempo real.', challenge: 'Criar uma plataforma para processar milhões de eventos por dia em tempo real.', solution: 'Provisionamento de um cluster Kafka no Kubernetes utilizando o operador Strimzi para simplificar o gerenciamento e garantir alta disponibilidade.', result: 'Capacidade para processar mais de 2 milhões de eventos por dia.', tools: [{ name: 'kafka', category: 'Aplicação & Dados', usage: 'Plataforma de streaming para ingestão de milhões de eventos.'}, { name: 'kubernetes', category: 'Cloud & SRE', usage: 'Ambiente de orquestração para o cluster Kafka.'}, { name: 'python', category: 'Aplicação & Dados', usage: 'Linguagem para consumidores e produtores de eventos Kafka.'}], borderColor: 'interactive-border-yellow', metric: { value: '+2M', label: 'Eventos/Dia', explanation: 'A plataforma foi construída para processar mais de 2 milhões de eventos por dia, permitindo análises em tempo real.' }, breakdown: { app_data: 60, cloud: 40 } },
    { id: 1, category: 'DevSecOps', title: 'Automação de Pipeline Seguro', description: 'Pipeline CI/CD seguro e agnóstico de nuvem com GitHub Actions e verificação de segurança.', challenge: 'Padronizar o processo de CI/CD para mais de 10 equipes.', solution: 'Criação de um pipeline reutilizável com GitHub Actions que executa SAST (SonarQube) e SCA (Snyk) em cada pull request.', result: 'Apenas código verificado é enviado para o deploy via ArgoCD.', tools: [{ name: 'githubactions', category: 'DevSecOps', usage: 'Orquestração do pipeline de CI/CD.'}, { name: 'sonarqube', category: 'DevSecOps', usage: 'Análise estática de segurança do código (SAST).'}, { name: 'snyk', category: 'DevSecOps', usage: 'Análise de composição de software para vulnerabilidades (SCA).'}], borderColor: 'interactive-border-sky', metric: { value: '+95%', label: 'Cobertura de Segurança', explanation: 'Aumentámos a cobertura de testes de segurança automatizados para mais de 95% do código, reduzindo drasticamente os riscos.' }, breakdown: { devops: 80, strategy: 20 } },
];

const articlesData = [
    { id: 0, title: 'AIOps na Prática', category: 'AIOps', insight: '"AIOps não é sobre substituir humanos, é sobre ampliar a sua capacidade de foco."', description: 'Uma análise sobre como a IA está a transformar a observabilidade de reativa para preditiva.', colorClass: 'purple', content: `<p>A observabilidade tradicional é reativa. Esperamos que um alerta dispare para começar a investigar. O AIOps inverte esta lógica.</p><p>Ao aplicar modelos de Machine Learning sobre métricas de séries temporais (como as do Prometheus), podemos identificar desvios subtis no comportamento normal de um sistema *antes* que eles se tornem incidentes críticos. Isto significa menos tempo em "salas de guerra" e mais tempo a inovar.</p><p>A verdadeira força do AIOps não é substituir engenheiros, mas sim filtrar o ruído, correlacionar eventos de múltiplas fontes (logs, métricas, traces) e apresentar uma causa provável, permitindo que a equipa de SRE se foque na solução estratégica em vez de perder horas a diagnosticar.</p>` },
    { id: 1, title: 'Implementando Zero Trust', category: 'Segurança', insight: '"Zero Trust não é um produto, é uma estratégia que começa na identidade, não no perímetro."', description: 'Uma visão técnica sobre como a segurança de rede moderna pode ser alcançada com eBPF.', colorClass: 'pink', content: `<p>O modelo de segurança baseado em perímetro (firewalls, VPNs) está obsoleto na era da nuvem. O Zero Trust parte do princípio de que nenhuma requisição, interna ou externa, é confiável por padrão.</p><p>Com ferramentas como o Cilium, que utiliza o poder do eBPF no kernel do Linux, podemos aplicar políticas de segurança baseadas na identidade criptográfica de um serviço, e não no seu endereço IP, que é efémero em ambientes de contêineres. Isto permite-nos criar regras granulares como "O serviço de pagamentos só pode comunicar com a base de dados de transações", independentemente de onde esses serviços estejam a correr.</p><p>O resultado é uma superfície de ataque drasticamente reduzida e uma segurança que se adapta dinamicamente à sua arquitetura.</p>` },
    { id: 2, title: 'O Futuro do DevOps', category: 'Platform Engineering', insight: '"A melhor métrica de um bom Platform Engineering é a autonomia, não a velocidade."', description: 'Como portais de self-service como o Backstage estão a redefinir a produtividade dos programadores.', colorClass: 'sky', content: `<p>A promessa do DevOps era quebrar os silos entre desenvolvimento e operações. No entanto, em muitas empresas, isto resultou em programadores sobrecarregados com a complexidade da infraestrutura (Kubernetes, Terraform, etc.).</p><p>O Platform Engineering resolve este problema. O objetivo é criar uma "plataforma interna" que abstrai a complexidade da infraestrutura e oferece aos programadores uma experiência de self-service. Com ferramentas como o Backstage, podemos criar um portal centralizado onde um programador pode, com poucos cliques, criar um novo microsserviço com todo o pipeline de CI/CD, segurança e observabilidade já configurados.</p><p>A métrica de sucesso deixa de ser a "velocidade de deploy" e passa a ser a "autonomia e produtividade do programador", o que gera um impacto muito maior no negócio.</p>` },
    { id: 3, title: 'Gerindo Custos na Nuvem', category: 'FinOps', insight: '"FinOps é a prática de trazer responsabilidade financeira para os custos variáveis da nuvem."', description: 'Uma abordagem sobre como otimizar custos sem sacrificar a performance.', colorClass: 'green', content: `<p>Conteúdo do artigo sobre FinOps...</p>`},
    { id: 4, title: 'Engenharia de Dados Moderna', category: 'Data Engineering', insight: '"O valor não está nos dados, mas na velocidade e fiabilidade com que os transformamos em insights."', description: 'Como plataformas de streaming como o Kafka são a base dos negócios em tempo real.', colorClass: 'yellow', content: `<p>Conteúdo do artigo sobre Engenharia de Dados...</p>`},
    { id: 5, title: 'O Paradoxo da Resiliência', category: 'SRE', insight: '"Um sistema verdadeiramente resiliente não é aquele que nunca falha, mas aquele que se recupera de forma tão rápida que o utilizador não percebe."', description: 'Uma reflexão sobre como a Engenharia de Caos nos ajuda a construir sistemas mais robustos.', colorClass: 'orange', content: `<p>Conteúdo do artigo sobre SRE e Engenharia de Caos...</p>`},
];

const testimonialsData = [
    { type: 'video', quote: '"A combinação da profundidade técnica com a gestão de projeto exemplar foi o fator decisivo para o sucesso da nossa migração."', author: 'Jane Doe', title: 'CTO, Empresa de Tecnologia', linkedin: '#', thumbnail: 'https://placehold.co/600x400/0ea5e9/white?text=Ver+V%C3%ADdeo', colorClass: 'sky', companyLogo: 'https://placehold.co/100x40/ffffff/0a0a0a?text=TechCorp', relatedProject: { title: 'Migração para Microsserviços K8s', metric: '-90% Downtime' } },
    { type: 'text', quote: '"A abordagem proativa de SRE e IA para monitoramento permitiu-nos focar 100% no desenvolvimento de novas funcionalidades."', author: 'John Smith', title: 'Head of Engineering, Startup de SaaS', linkedin: '#', colorClass: 'purple', companyLogo: 'https://placehold.co/100x40/ffffff/0a0a0a?text=SaaSify', relatedProject: { title: 'Sistema Preditivo com AIOps', metric: '-60% MTTR' } },
    { type: 'text', quote: '"O pipeline automatizado e seguro que foi construído reduziu o nosso tempo de entrega e aumentou drasticamente a nossa segurança."', author: 'Emily White', title: 'Product Manager, Fintech', linkedin: '#', colorClass: 'sky', companyLogo: 'https://placehold.co/100x40/ffffff/0a0a0a?text=FintechCo', relatedProject: { title: 'Automação de Pipeline Seguro', metric: '+95% Cobertura de Segurança' } }
];

const testimonialsData = [
    { type: 'video', quote: '"A combinação da profundidade técnica com a gestão de projeto exemplar foi o fator decisivo para o sucesso da nossa migração."', author: 'Jane Doe', title: 'CTO, Empresa de Tecnologia', linkedin: '#', thumbnail: 'https://placehold.co/600x400/0ea5e9/white?text=Ver+V%C3%ADdeo', colorClass: 'sky', companyLogo: 'https://placehold.co/100x40/ffffff/0a0a0a?text=TechCorp', relatedProject: { title: 'Migração para Microsserviços K8s', metric: '-90% Downtime' } },
    { type: 'text', quote: '"A abordagem proativa de SRE e IA para monitoramento permitiu-nos focar 100% no desenvolvimento de novas funcionalidades."', author: 'John Smith', title: 'Head of Engineering, Startup de SaaS', linkedin: '#', colorClass: 'purple', companyLogo: 'https://placehold.co/100x40/ffffff/0a0a0a?text=SaaSify', relatedProject: { title: 'Sistema Preditivo com AIOps', metric: '-60% MTTR' } },
    { type: 'text', quote: '"O pipeline automatizado e seguro que foi construído reduziu o nosso tempo de entrega e aumentou drasticamente a nossa segurança."', author: 'Emily White', title: 'Product Manager, Fintech', linkedin: '#', colorClass: 'sky', companyLogo: 'https://placehold.co/100x40/ffffff/0a0a0a?text=FintechCo', relatedProject: { title: 'Automação de Pipeline Seguro', metric: '+95% Cobertura de Segurança' } }
];
